name: Run E2E workflow
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 12.x # Set the Node.js version to use.

jobs:
  run_e2e_test:
    name: Run all Gauge test scenarios
    # Find more virtual environment. https://github.com/actions/virtual-environments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the latest source code from the current branch
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ env.NODE_VERSION }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Gauge CLI
        run: npm install -g @getgauge/cli

      - name: Run all test scenarios
        run: |
          yarn install
          yarn run test
