name: Run E2E workflow
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 12.x # Set the Node.js version to use.
  DOCKER_IMAGE_NAME: ${{ secrets.LOGIN_SERVER }}/gauge-example:${{ github.sha }}

jobs:
  run_e2e_test:
    name: Run all Gauge test scenarios
    # Find more virtual environment. https://github.com/actions/virtual-environments
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the latest source code from the current branch
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ env.NODE_VERSION }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Gauge CLI
        run: npm install -g @getgauge/cli

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Run all test scenarios
        run: |
          yarn install
          yarn run test

      - name: Push a new image to container registry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}

        # Before downloading a publish profile, make sure that you have set WEBSITE_WEBDEPLOY_USE_SCM
        # in App Service Configuration to true
        # configure port number 
        # https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#configure-port-number
        # WEBSITES_PORT
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_CONTAINER_PUBLISH_PROFILE }}
          images: ${{ env.DOCKER_IMAGE_NAME }}
